[package]
name = "fom-tools-cli"
version = "0.1.0"
authors = ["Anthony Cramp <anthony.cramp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
